<?php
/**
 * Gateway Lodge Group : per-property content for the Elementor builder.
 *
 * GENERATED by tools/build-wp-property-content.py from PROPERTIES in
 * tools/build-landings.py, so the WordPress build and the static pages cannot
 * drift apart. Do not hand-edit: change the copy at the source and re-run.
 */

return array(
	'novaridge' => array(
		'slug' => 'novaridge',
		'property' => 'Gateway Nova Ridge',
		'short' => 'Nova Ridge',
		'locality' => 'Ridge, Accra',
		'region' => 'Greater Accra',
		'address' => '4 Drake Avenue area, Ridge, Accra, Ghana',
		'units' => '1 Unit',
		'phone' => '+233 24 000 0000',
		'whatsapp' => 'https://wa.me/233240000000',
		'email' => 'reservations@gatewaylodgegroup.com',
		'group' => 'https://www.gatewaylodgegroup.com',
		'site' => 'https://novaridge.gatewaylodgegroup.com',
		'map_address' => '4 Drake Avenue area, Ridge, Accra, Ghana',
		'tagline' => 'A private high-rise residence in Accra&rsquo;s most established address, kept to the Gateway Lodge standard and yours alone for the length of your stay.',
		'meta_desc' => 'Gateway Nova Ridge is a private, fully serviced apartment in Ridge, Accra: one unit, floor-to-ceiling city views and the full Gateway Lodge Group standard of hospitality. Book direct.',
		'hero_video' => 'novaridge-tour',
		'hero_poster' => 'hero-living',
		'stats' => array(
			array(
				'1',
				'Private unit',
			),
			array(
				'2',
				'Bedrooms',
			),
			array(
				'24/7',
				'Guest support',
			),
			array(
				'15 min',
				'To the airport',
			),
		),
		'pillars' => array(
			array(
				'Yours alone',
				'A single unit, so the apartment is never shared, split or reassigned mid-stay.',
			),
			array(
				'Built for longer stays',
				'A real kitchen, laundry and a desk: the things that matter after night three.',
			),
			array(
				'A settled address',
				'Ridge puts the ministries, the CBD and Kotoka within an easy drive.',
			),
		),
		'about_kicker' => 'The Residence',
		'about_head' => 'One apartment. No lobby, no queue, no neighbours in the corridor.',
		'about_body' => array(
			'Nova Ridge is a single serviced apartment on an upper floor of a residential tower in Ridge, the quiet tree-lined district that sits between central Accra&rsquo;s business addresses and the embassies. You are not checking into a hotel floor. You arrive to an apartment that has been prepared for you and stays that way.',
			'Inside: an open living room that runs into a full kitchen, a dining table, two bedrooms dressed in hotel linen, two bathrooms, and a balcony that looks out over the green of Ridge towards the city. It suits the guest who is in Accra for a fortnight as easily as the one here for two nights.',
		),
		'about_image' => 'lounge-open-plan',
		'rooms' => array(
			array(
				'bedroom-king',
				'Principal Bedroom',
				'A king bed, blackout curtains, fitted wardrobes and an en-suite bathroom.',
			),
			array(
				'bedroom-second',
				'Second Bedroom',
				'A second double room with its own wardrobe and mirror, for family or a colleague.',
			),
			array(
				'lounge-tv-wall',
				'Living Room',
				'Deep seating for six, a smart television and light on two sides through the day.',
			),
			array(
				'kitchen-wide',
				'Kitchen &amp; Dining',
				'A full fitted kitchen with oven, hob, microwave and a dining table for four.',
			),
		),
		'facilities_head' => 'Everything the apartment needs, already in it',
		'facilities_body' => 'Nothing here is an upgrade or an extra line on the folio. The apartment arrives complete, and the team keeps it that way for as long as you stay.',
		'facilities_image' => 'kitchen',
		'facilities' => array(
			array(
				'fas fa-wifi',
				'High-Speed Wi-Fi',
				'Fibre throughout the apartment, steady enough for calls and uploads.',
			),
			array(
				'fas fa-utensils',
				'Full Kitchen',
				'Oven, hob, microwave, fridge-freezer, kettle and a stocked utensil drawer.',
			),
			array(
				'fas fa-snowflake',
				'Air Conditioning',
				'Individually controlled in every bedroom and the living room.',
			),
			array(
				'fas fa-bolt',
				'Backup Power',
				'The building runs on standby power, so the apartment stays on.',
			),
			array(
				'fas fa-tshirt',
				'Laundry',
				'In-apartment washing, with a pressing and laundry service on request.',
			),
			array(
				'fas fa-laptop',
				'Desk &amp; Workspace',
				'A proper surface to work from, not a chair pulled up to the dining table.',
			),
			array(
				'fas fa-tree',
				'Private Balcony',
				'Table and chairs, and a long view over the Ridge treeline.',
			),
			array(
				'fas fa-car',
				'Secure Parking',
				'Gated, monitored parking within the building for one vehicle.',
			),
			array(
				'fas fa-shield-alt',
				'24-Hour Security',
				'Manned entry and CCTV across the building&rsquo;s common areas.',
			),
			array(
				'fas fa-concierge-bell',
				'Guest Support',
				'One number, answered at any hour, for anything the stay needs.',
			),
			array(
				'fas fa-elevator',
				'Lift Access',
				'Serviced lifts to the apartment floor.',
			),
			array(
				'fas fa-broom',
				'Housekeeping',
				'Scheduled servicing and fresh linen, arranged around you.',
			),
		),
		'gallery_home' => array(
			'hero-living',
			'lounge-tv-wall',
			'kitchen-dining',
			'bedroom-suite',
			'balcony-skyline',
			'lounge-daylight',
		),
		'gallery_facilities' => array(
			'bedroom-window',
			'dining-nook',
			'bathroom',
			'hallway',
			'lounge-sofas',
			'balcony',
		),
		'banner_about' => 'lounge-open-plan',
		'banner_facilities' => 'kitchen',
		'banner_contact' => 'hallway',
		'about_sections' => array(
			array(
				'kicker' => 'Who we are',
				'head' => 'A hotel standard, in a home that is only yours.',
				'paras' => array(
					'Gateway Nova Ridge is the smallest and most private of the three Gateway Lodge properties: one apartment, on an upper floor of a residential tower in Ridge. There is no reception floor and no corridor of other guests. You let yourself in, and for as long as you stay the apartment belongs to you.',
					'Inside there is an open living room that runs into a full kitchen, a dining table, two bedrooms dressed in hotel linen, two bathrooms, and a balcony looking over the green of Ridge towards the city.',
				),
			),
			array(
				'kicker' => 'The address',
				'head' => 'Ridge, where Accra keeps its quiet.',
				'paras' => array(
					'Ridge is the district of embassies, ministries and old trees, a few minutes from the central business district but a world away from its noise. It is the address people choose when they want to be close to everything and hear none of it.',
				),
			),
			array(
				'kicker' => 'How we run it',
				'head' => 'Serviced, not staffed over.',
				'paras' => array(
					'Housekeeping comes on a rhythm that suits your stay rather than a fixed hotel schedule. Laundry, pressing, airport transfers and grocery runs are arranged on request. One number reaches the team at any hour.',
				),
			),
		),
		'banner_subs' => array(
			'about' => 'A single serviced apartment in Ridge, run to the Gateway Lodge standard.',
			'facilities' => 'Everything an extended stay asks for is already fitted.',
			'contact' => 'Reservations answer by phone and WhatsApp every day.',
		),
		'location_points' => array(
			'Walking distance to Ridge&rsquo;s embassies and government offices',
			'About 15 minutes by car to Kotoka International Airport',
			'Ten minutes to Osu, Airport Residential and the CBD',
			'Ridge Hospital and Accra&rsquo;s main clinics close by',
		),
		'faqs' => array(
			array(
				'Is the whole apartment mine?',
				'Yes. Nova Ridge is a single unit, so it is never shared or split between parties.',
			),
			array(
				'Do you take long stays?',
				'We do. The kitchen, laundry and workspace are built for stays measured in weeks rather than nights. Ask reservations about the long-stay rate.',
			),
			array(
				'Is parking included?',
				'Yes, one gated parking space within the building comes with the apartment.',
			),
			array(
				'What happens in a power cut?',
				'The building runs on standby power, so the apartment stays lit and cooled.',
			),
		),
		'seo' => array(
			'about' => array(
				'About Gateway Nova Ridge | Ridge, Accra',
				'One serviced apartment on an upper floor in Ridge, Accra. No lobby, no shared corridor: the apartment is yours alone for the length of your stay.',
			),
			'facilities' => array(
				'Facilities & Amenities | Gateway Nova Ridge, Accra',
				'Full kitchen, in-apartment laundry, air conditioning, backup power, secure parking, private balcony and 24-hour support at Gateway Nova Ridge.',
			),
			'contact' => array(
				'Contact & Location | Gateway Nova Ridge, Ridge, Accra',
				'Find Gateway Nova Ridge in Ridge, Accra. Call or WhatsApp reservations, or send the enquiry form for availability and rates.',
			),
		),
	),
	'lakeside' => array(
		'slug' => 'lakeside',
		'property' => 'Gateway Lodge Lakeside',
		'short' => 'Lakeside',
		'locality' => 'Lakeside, Accra',
		'region' => 'Greater Accra',
		'address' => 'Lakeside Estate, Accra, Ghana',
		'units' => '12 Units',
		'phone' => '+233 24 000 0000',
		'whatsapp' => 'https://wa.me/233240000000',
		'email' => 'reservations@gatewaylodgegroup.com',
		'group' => 'https://www.gatewaylodgegroup.com',
		'site' => 'https://lakeside.gatewaylodgegroup.com',
		'map_address' => 'Lakeside Estate, Accra, Ghana',
		'tagline' => 'Twelve units on the quiet side of Accra, where the drive home ends beside the water instead of in the traffic.',
		'meta_desc' => 'Gateway Lodge Lakeside offers twelve serviced rooms and units in Lakeside Estate, Accra, with calm surroundings, full facilities and the Gateway Lodge Group standard of hospitality. Book direct.',
		'hero_video' => null,
		'hero_poster' => '726ee4b1-f8fd-45a0-bd12-98235b1d3c98',
		'stats' => array(
			array(
				'12',
				'Rooms and units',
			),
			array(
				'24/7',
				'Front desk',
			),
			array(
				'On site',
				'Dining',
			),
			array(
				'Free',
				'Parking',
			),
		),
		'pillars' => array(
			array(
				'Room for a group',
				'Twelve units means a family, a team or a small event fits in one place.',
			),
			array(
				'Genuinely quiet',
				'Residential surroundings and grounds, rather than a main-road frontage.',
			),
			array(
				'Full service',
				'A staffed front desk, dining on site and housekeeping every day.',
			),
		),
		'about_kicker' => 'The Lodge',
		'about_head' => 'The largest of the three, and the calmest.',
		'about_body' => array(
			'Lakeside sits east of the centre in the Lakeside Estate, far enough out that the evenings are quiet and close enough that the city is still a drive rather than a journey. Twelve rooms and units, a front desk that is staffed around the clock, and grounds you can actually walk in.',
			'It is the property guests choose when they are travelling as a family, when a team needs several rooms under one roof, or when the point of the trip is to slow down for a few days.',
		),
		'about_image' => '9b1028a4-660c-497a-9914-83998ffb6fb7',
		'rooms' => array(
			array(
				'tm-bedroom-suite',
				'Lakeside Suite',
				'The largest category: a king bed, a separate seating area and a full bathroom.',
			),
			array(
				'nr-bedroom-second',
				'Twin Room',
				'Two beds and a garden outlook, for colleagues travelling together or a family.',
			),
			array(
				'nr-lounge-open-plan',
				'Serviced Unit',
				'A kitchenette, a living area and a desk, built for stays measured in weeks.',
			),
			array(
				'nr-bedroom-king',
				'Double Room',
				'A comfortable double with everything a short stay needs, nothing it does not.',
			),
		),
		'facilities_head' => 'A lodge that runs properly, every day',
		'facilities_body' => 'Twelve units is the size where service either holds or slips. Lakeside is staffed to hold it: a desk that is always answered, kitchen hours that suit real arrivals, and housekeeping that does not need chasing.',
		'facilities_image' => 'nr-lounge-dining',
		'facilities' => array(
			array(
				'fas fa-concierge-bell',
				'24-Hour Front Desk',
				'Staffed through the night for late arrivals and early departures.',
			),
			array(
				'fas fa-wifi',
				'High-Speed Wi-Fi',
				'Covered across the rooms and the common areas.',
			),
			array(
				'fas fa-snowflake',
				'Air Conditioning',
				'In every room, individually controlled.',
			),
			array(
				'fas fa-utensils',
				'On-Site Dining',
				'Breakfast daily, with lunch and dinner served to order.',
			),
			array(
				'fas fa-broom',
				'Daily Housekeeping',
				'Rooms serviced every day, linen changed on schedule.',
			),
			array(
				'fas fa-bolt',
				'Backup Power',
				'Standby generation so the property stays lit and cool.',
			),
			array(
				'fas fa-tint',
				'Lakeside Grounds',
				'Walkable grounds and seating out by the water.',
			),
			array(
				'fas fa-car',
				'Ample Parking',
				'On-site parking for guests, at no extra charge.',
			),
			array(
				'fas fa-shield-alt',
				'24-Hour Security',
				'Manned gate and patrolled grounds.',
			),
			array(
				'fas fa-tshirt',
				'Laundry Service',
				'Same-day laundry and pressing on request.',
			),
			array(
				'fas fa-users',
				'Family Friendly',
				'Connecting arrangements and extra beds available.',
			),
			array(
				'fas fa-tv',
				'Meetings &amp; Events',
				'Space for a small board meeting, a birthday or a family gathering.',
			),
		),
		'gallery_home' => array(
			'726ee4b1-f8fd-45a0-bd12-98235b1d3c98',
			'nr-hero-living',
			'tm-living-lounge',
			'84eced95-da88-4037-adc3-b8ea69c30f30',
			'nr-kitchen-dining',
			'9b1028a4-660c-497a-9914-83998ffb6fb7',
		),
		'gallery_facilities' => array(
			'tm-kitchen-wide',
			'nr-bathroom',
			'tm-terrace',
			'nr-balcony-skyline',
			'tm-bathroom-shower',
			'860bbcfd-9e64-4281-b392-e2d06ac5b441',
		),
		'banner_about' => '9b1028a4-660c-497a-9914-83998ffb6fb7',
		'banner_facilities' => 'nr-lounge-dining',
		'banner_contact' => '860bbcfd-9e64-4281-b392-e2d06ac5b441',
		'about_sections' => array(
			array(
				'kicker' => 'Who we are',
				'head' => 'The largest of the three, and the calmest.',
				'paras' => array(
					'Gateway Lodge Lakeside sits east of the centre in the Lakeside Estate, far enough out that the evenings are quiet and close enough that the city is still a drive rather than a journey. Twelve rooms and units, a front desk staffed around the clock, and grounds you can actually walk in.',
					'It is the property guests choose when they are travelling as a family, when a team needs several rooms under one roof, or when the point of the trip is to slow down for a few days.',
				),
			),
			array(
				'kicker' => 'The address',
				'head' => 'Far enough out that the evening goes quiet.',
				'paras' => array(
					'Lakeside Estate is residential rather than commercial, so the noise stops when the day does. The eastern suburbs and the Accra to Aburi road are close, and the centre is a straightforward drive rather than a fight through traffic.',
				),
			),
			array(
				'kicker' => 'How we run it',
				'head' => 'A desk that is always answered.',
				'paras' => array(
					'Twelve units is the size where service either holds or slips. Lakeside is staffed to hold it: a front desk through the night for late arrivals, breakfast every morning with lunch and dinner to order, and housekeeping that does not need chasing.',
				),
			),
		),
		'banner_subs' => array(
			'about' => 'Twelve rooms and units on the quiet side of Accra.',
			'facilities' => 'A staffed desk, dining on site and grounds to walk in.',
			'contact' => 'Reservations answer by phone and WhatsApp every day.',
		),
		'location_points' => array(
			'Set inside Lakeside Estate, away from the main-road noise',
			'Around 40 minutes by car to Kotoka International Airport',
			'Easy reach of the Accra&ndash;Aburi road and the eastern suburbs',
			'Shops, pharmacies and fuel within a few minutes&rsquo; drive',
		),
		'faqs' => array(
			array(
				'Can you take a group?',
				'Yes. Twelve rooms and units means a family, a team or a small event can stay under one roof. Tell reservations how many of you there are and we will hold the right mix.',
			),
			array(
				'Is breakfast included?',
				'Breakfast is served daily, with lunch and dinner cooked to order. Ask when you book.',
			),
			array(
				'How far is the airport?',
				'About 40 minutes by car to Kotoka International Airport, traffic depending.',
			),
			array(
				'Is there parking?',
				'Yes, on-site parking for guests at no extra charge, behind a manned gate.',
			),
		),
		'seo' => array(
			'about' => array(
				'About Gateway Lodge Lakeside | Accra',
				'Twelve serviced rooms and units in Lakeside Estate, Accra: quiet surroundings, a staffed front desk and dining on site.',
			),
			'facilities' => array(
				'Facilities & Amenities | Gateway Lodge Lakeside, Accra',
				'24-hour front desk, on-site dining, daily housekeeping, backup power, grounds and ample parking at Gateway Lodge Lakeside.',
			),
			'contact' => array(
				'Contact & Location | Gateway Lodge Lakeside, Accra',
				'Find Gateway Lodge Lakeside in Lakeside Estate, Accra. Call or WhatsApp reservations, or send the enquiry form.',
			),
		),
	),
	'tamale' => array(
		'slug' => 'tamale',
		'property' => 'Gateway Lodge Tamale',
		'short' => 'Tamale',
		'locality' => 'Tamale, Northern Region',
		'region' => 'Northern Region',
		'address' => 'Tamale, Northern Region, Ghana',
		'units' => '6 Units',
		'phone' => '+233 24 000 0000',
		'whatsapp' => 'https://wa.me/233240000000',
		'email' => 'reservations@gatewaylodgegroup.com',
		'group' => 'https://www.gatewaylodgegroup.com',
		'site' => 'https://tamale.gatewaylodgegroup.com',
		'map_address' => 'Tamale, Northern Region, Ghana',
		'tagline' => 'Six fully furnished apartments in Tamale, built for the way people actually work in the north, for a night, a week, or a whole season.',
		'meta_desc' => 'Gateway Lodge Tamale offers six fully furnished one and two-bedroom serviced apartments in Tamale, Northern Region, for short and long stays, secure parking and full facilities. Book direct.',
		'hero_video' => 'tamale-tour',
		'hero_poster' => 'hero-courtyard',
		'stats' => array(
			array(
				'6',
				'Furnished apartments',
			),
			array(
				'1 &amp; 2',
				'Bedroom layouts',
			),
			array(
				'Short &amp; long',
				'Stays',
			),
			array(
				'24/7',
				'Security',
			),
		),
		'pillars' => array(
			array(
				'Made for the long stay',
				'Full kitchens, laundry and living space in every apartment.',
			),
			array(
				'One or two bedrooms',
				'Sized for a single traveller, a colleague pair or a family.',
			),
			array(
				'Purpose-built and walled',
				'A gated block with its own courtyard parking, not a converted house.',
			),
		),
		'about_kicker' => 'The Apartments',
		'about_head' => 'A base in the north, not a room for the night.',
		'about_body' => array(
			'Tamale is the working capital of northern Ghana, and most people who come here come for a stretch: a project, a posting, a season of fieldwork. Gateway Lodge Tamale is built for exactly that: six fully furnished apartments in a purpose-built, walled block, in one and two-bedroom layouts.',
			'Each apartment has its own kitchen, its own living room and its own bathroom, so a long stay does not mean living out of a suitcase. Housekeeping, laundry, secure parking and a manned gate come with it.',
		),
		'about_image' => 'exterior-frontage',
		'rooms' => array(
			array(
				'bedroom-king',
				'One-Bedroom Apartment',
				'A double bedroom, a full living room, kitchen and bathroom, for one or two guests.',
			),
			array(
				'living-lounge',
				'Two-Bedroom Apartment',
				'Two bedrooms off a shared living room, the layout families and pairs of colleagues take.',
			),
			array(
				'kitchen',
				'Private Kitchen',
				'Cooker, fridge, microwave, washing machine and worktop space in every apartment.',
			),
			array(
				'terrace',
				'Shared Terrace',
				'A covered terrace off the upper walkway, for the hours after the heat drops.',
			),
		),
		'facilities_head' => 'Set up for a working stay in the north',
		'facilities_body' => 'Everything an extended stay in Tamale asks for is already fitted: power that holds through an outage, cooling in every room, a kitchen you can cook a real meal in, and parking behind a gate.',
		'facilities_image' => 'living-tv',
		'facilities' => array(
			array(
				'fas fa-utensils',
				'Private Kitchen',
				'Cooker, fridge, microwave and full worktop in every apartment.',
			),
			array(
				'fas fa-tshirt',
				'Washing Machine',
				'In-apartment laundry, plus a pressing service on request.',
			),
			array(
				'fas fa-snowflake',
				'Air Conditioning &amp; Fans',
				'Split units and ceiling fans in the bedrooms and living rooms.',
			),
			array(
				'fas fa-bolt',
				'Backup Power',
				'Standby generation covering the whole block.',
			),
			array(
				'fas fa-wifi',
				'Wi-Fi',
				'Internet across the apartments and the common areas.',
			),
			array(
				'fas fa-tv',
				'Smart Television',
				'A mounted television in each living room.',
			),
			array(
				'fas fa-car',
				'Gated Parking',
				'Courtyard parking inside the walls, with a manned gate.',
			),
			array(
				'fas fa-shield-alt',
				'24-Hour Security',
				'A walled compound with security on site day and night.',
			),
			array(
				'fas fa-broom',
				'Housekeeping',
				'Scheduled cleaning and fresh linen, at a rhythm that suits your stay.',
			),
			array(
				'fas fa-tint',
				'Water Storage',
				'Stored and pumped supply, so the taps do not depend on the mains.',
			),
			array(
				'fas fa-tree',
				'Terrace &amp; Walkway',
				'Shaded outdoor seating on the upper level.',
			),
			array(
				'fas fa-plane',
				'Airport Runs',
				'Transfers to and from Tamale Airport arranged on request.',
			),
		),
		'gallery_home' => array(
			'hero-courtyard',
			'living-lounge',
			'bedroom-king',
			'kitchen-wide',
			'living-open',
			'bedroom-tv',
		),
		'gallery_facilities' => array(
			'bathroom',
			'dining-nook',
			'terrace',
			'exterior-street',
			'stairwell',
			'entrance-gate',
		),
		'banner_about' => 'exterior-frontage',
		'banner_facilities' => 'living-tv',
		'banner_contact' => 'stairwell',
		'about_sections' => array(
			array(
				'kicker' => 'Who we are',
				'head' => 'A base in the north, not a room for the night.',
				'paras' => array(
					'Tamale is the working capital of northern Ghana, and most people who come here come for a stretch: a project, a posting, a season of fieldwork. Gateway Lodge Tamale is built for exactly that: six fully furnished apartments in a purpose-built, walled block, in one and two-bedroom layouts.',
					'Each apartment has its own kitchen, its own living room and its own bathroom, so a long stay does not mean living out of a suitcase.',
				),
			),
			array(
				'kicker' => 'The address',
				'head' => 'Tamale, and the work that brings you here.',
				'paras' => array(
					'The block sits within reach of the central business area and the markets, a short drive from Tamale International Airport, and convenient for Northern Region project sites and NGO offices. Banks, fuel and supermarkets are close by.',
				),
			),
			array(
				'kicker' => 'How we run it',
				'head' => 'Serviced around a working week.',
				'paras' => array(
					'Housekeeping and fresh linen come at a rhythm that suits the length of your stay rather than a fixed hotel schedule. Laundry, pressing and airport transfers are arranged on request, and the gate is manned day and night.',
				),
			),
		),
		'banner_subs' => array(
			'about' => 'Six furnished apartments in a walled block in Tamale.',
			'facilities' => 'Private kitchens, laundry and power that holds.',
			'contact' => 'Reservations answer by phone and WhatsApp every day.',
		),
		'location_points' => array(
			'In Tamale, within reach of the central business area and the markets',
			'A short drive from Tamale International Airport',
			'Convenient for Northern Region project sites and NGO offices',
			'Banks, fuel and supermarkets close by',
		),
		'faqs' => array(
			array(
				'Do you take long stays?',
				'Yes, and most guests are here for a stretch. Every apartment has its own kitchen and laundry, and there is a rate for stays by the month.',
			),
			array(
				'One bedroom or two?',
				'Both. One-bedroom apartments suit a single traveller or a pair; two-bedroom apartments suit families and colleagues sharing.',
			),
			array(
				'Is the compound secure?',
				'It is a walled, purpose-built block with courtyard parking, a manned gate and security on site day and night.',
			),
			array(
				'What happens in a power cut?',
				'Standby generation covers the whole block, and water is stored and pumped rather than depending on the mains.',
			),
		),
		'seo' => array(
			'about' => array(
				'About Gateway Lodge Tamale | Northern Region',
				'Six fully furnished one and two-bedroom serviced apartments in Tamale, built for stays measured in weeks rather than nights.',
			),
			'facilities' => array(
				'Facilities & Amenities | Gateway Lodge Tamale',
				'Private kitchens, in-apartment laundry, air conditioning, backup power, gated parking and 24-hour security at Gateway Lodge Tamale.',
			),
			'contact' => array(
				'Contact & Location | Gateway Lodge Tamale, Northern Region',
				'Find Gateway Lodge Tamale in the Northern Region. Call or WhatsApp reservations, or send the enquiry form.',
			),
		),
	),
);
